version: '2'
services:
  webapi:
    image: apiicecream:latest
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings:PostgreSQLConnection=Server=postgres;Port=5432;Database=IceStore;User Id=postgres;Password=admin;
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=IceStore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin